language: python

python:
  - "2.7"

before_install:
  - pip install numpy
  - pip install scipy
  - pip install pandas
  - pip install laspy
  - pip install patch

script:
  - python src/build/build.py -x64
  - python test_suite.py
